# Generated by Django 4.1.7 on 2023-02-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addmovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=30, null=True)),
                ('Description', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=30, null=True)),
                ('time', models.CharField(max_length=30, null=True)),
                ('Date', models.DateField(null=True)),
                ('Date1', models.DateField(null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
    ]
