# Generated by Django 4.1.7 on 2023-03-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_addmovies_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre_data',
            name='qrcode',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
