# Generated by Django 4.1.7 on 2023-03-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_theatre_data_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmovies',
            name='no_tickets',
            field=models.IntegerField(null=True),
        ),
    ]
