# Generated by Django 4.1.7 on 2023-03-01 19:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_user_data1_delete_user_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_data1',
            new_name='user_data',
        ),
    ]
