# Generated by Django 4.1.7 on 2023-03-01 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_rename_user_data1_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='theatre_data1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstno', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('License_No', models.IntegerField(null=True)),
                ('phone', models.IntegerField(null=True)),
                ('Facilities', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('specification', models.CharField(max_length=30, null=True)),
                ('qrcode', models.ImageField(null=True, upload_to='')),
                ('tuser_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='theatre_data',
        ),
    ]
