# Generated by Django 4.1.7 on 2023-03-01 20:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_theatre_data1_delete_theatre_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='theatre_data1',
            new_name='theatre_data',
        ),
    ]
