# Generated by Django 4.1.7 on 2023-03-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_addmovies1_delete_addmovies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addmovies1',
            new_name='addmovies',
        ),
    ]
