# Generated by Django 4.1.7 on 2023-03-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_booked_data1_booked_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked_data',
            name='theatre_name',
        ),
    ]
