# Generated by Django 4.1.7 on 2023-03-02 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_booked_data_theatre_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='booked_data1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30, null=True)),
                ('movie_name', models.CharField(max_length=30, null=True)),
                ('showtime', models.CharField(max_length=30, null=True)),
                ('Date', models.DateField(null=True)),
                ('price_1_tk', models.IntegerField(null=True)),
                ('no_tickets', models.IntegerField(null=True)),
                ('screenshot', models.ImageField(null=True, upload_to='')),
                ('Total_amount', models.IntegerField(null=True)),
                ('theatre_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.theatre_data')),
            ],
        ),
        migrations.DeleteModel(
            name='booked_data',
        ),
    ]
