# Generated by Django 4.1.7 on 2023-03-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_booked_data1_delete_booked_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booked_data1',
            new_name='booked_data',
        ),
    ]
