# Generated by Django 4.1.7 on 2023-03-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_booked_data1_booked_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked_data',
            old_name='theatre_name',
            new_name='theatre',
        ),
    ]
