# Generated by Django 4.1.7 on 2023-03-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_theatre_name_booked_data_theatre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmovies',
            old_name='theatre_name',
            new_name='theatre',
        ),
    ]
