# Generated by Django 4.1.7 on 2023-03-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_theatre_name_addmovies_theatre'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre_data',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
    ]
