# Generated by Django 4.1.7 on 2023-03-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbacku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
