# Generated by Django 4.1.7 on 2023-03-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_feedbacku'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmovies',
            name='no_s',
            field=models.IntegerField(null=True),
        ),
    ]
