# Generated by Django 4.1.7 on 2023-03-12 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_booked_data_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=30, null=True)),
                ('Director', models.CharField(max_length=30, null=True)),
                ('caste', models.CharField(max_length=30, null=True)),
                ('Category', models.CharField(max_length=30, null=True)),
                ('Language', models.CharField(max_length=30, null=True)),
                ('Date', models.DateField(null=True)),
                ('Date1', models.DateField(null=True)),
                ('set_show', models.CharField(max_length=30, null=True)),
                ('no_tickets', models.IntegerField(null=True)),
                ('no_screen', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.theatre_data')),
            ],
        ),
    ]
