# Generated by Django 3.2.16 on 2023-05-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_payments_delete_addmovies'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked_data',
            name='seat_no',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
